# Generated by Django 3.0.7 on 2020-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('level', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, default='hello')),
                ('image', models.ImageField(blank=True, upload_to='StaticQuestions/images')),
                ('image_url', models.URLField(blank=True)),
                ('hint', models.TextField(blank=True, default='hint')),
                ('answer', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
