# Generated by Django 3.0.7 on 2020-07-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_stage_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage_2',
            name='background',
            field=models.FileField(blank=True, upload_to='AudioQuestions/music'),
        ),
        migrations.AlterField(
            model_name='stage_2',
            name='files',
            field=models.FileField(blank=True, upload_to='AudioQuestions/music'),
        ),
    ]
