# Generated by Django 3.0.7 on 2020-07-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200705_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetwo',
            name='level',
            field=models.IntegerField(unique=True),
        ),
    ]
