# Generated by Django 3.0.7 on 2020-07-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200705_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage_1',
            name='algo',
            field=models.TextField(blank=True),
        ),
    ]
