# Generated by Django 3.0.7 on 2020-07-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_stage_1_algo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetwo',
            name='level',
            field=models.IntegerField(),
        ),
    ]
