# Generated by Django 3.0.7 on 2020-07-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200717_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage_1',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stagetwo',
            name='background',
        ),
        migrations.RemoveField(
            model_name='stagetwo',
            name='files',
        ),
        migrations.RemoveField(
            model_name='stagetwo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stagetwo',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='stage_1',
            name='level',
            field=models.IntegerField(),
        ),
    ]
