# Generated by Django 3.0.7 on 2020-08-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_stagetwo_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage_1',
            name='algo',
            field=models.TextField(blank=True, default=' \n    <pre>\n    <code>\n\n    </code>\n    </pre>\n    '),
        ),
    ]
