# Generated by Django 3.0.7 on 2020-08-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200809_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage_1',
            name='algo',
            field=models.TextField(blank=True),
        ),
    ]
