# Generated by Django 4.2.1 on 2023-07-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20200830_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='regnolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(blank=True, max_length=4000)),
            ],
        ),
    ]
