# Generated by Django 4.2.1 on 2023-07-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_regnolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regnolist',
        ),
    ]
