# Generated by Django 3.0.7 on 2020-08-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaders',
            name='playerNum',
            field=models.IntegerField(default=10),
        ),
    ]
