# Generated by Django 3.0.7 on 2020-06-23 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
