# Generated by Django 3.0.7 on 2020-06-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200623_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='player',
            name='question_level',
            field=models.IntegerField(default=0),
        ),
    ]
