# Generated by Django 3.0.7 on 2020-07-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200624_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDetails',
            fields=[
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Player')),
                ('full_name', models.CharField(default='your name', max_length=400)),
                ('college', models.CharField(default='none', max_length=400)),
                ('year', models.CharField(default='1', max_length=10)),
                ('contact', models.BigIntegerField(blank=True, default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
