# Generated by Django 3.0.7 on 2020-07-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200702_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level2',
            field=models.IntegerField(default=1),
        ),
    ]
