# Generated by Django 3.0.7 on 2020-07-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_player_level2'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level2',
            field=models.IntegerField(default=-1),
        ),
    ]
