# Generated by Django 3.0.7 on 2020-07-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200706_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='count2',
            field=models.IntegerField(default=0),
        ),
    ]
