# Generated by Django 3.0.7 on 2020-07-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_player_count2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
