# Generated by Django 3.0.7 on 2020-07-16 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200716_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 2, 48, 8, 667622)),
        ),
    ]
