# Generated by Django 3.0.7 on 2020-07-20 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200720_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 19, 31, 29, 908663)),
        ),
    ]
