# Generated by Django 3.0.7 on 2020-08-09 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20200720_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 17, 44, 27, 659629)),
        ),
    ]
