# Generated by Django 3.0.7 on 2020-08-09 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20200809_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 19, 15, 5, 596745)),
        ),
    ]
