# Generated by Django 3.0.7 on 2020-08-11 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200809_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 21, 35, 32, 242585)),
        ),
        migrations.AlterField(
            model_name='player',
            name='level2',
            field=models.IntegerField(default=-2),
        ),
    ]
