# Generated by Django 3.0.7 on 2020-08-30 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200811_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 17, 34, 32, 945745)),
        ),
    ]
