# Generated by Django 3.0.7 on 2020-08-30 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20200830_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 21, 58, 34, 32663)),
        ),
    ]
