# Generated by Django 3.0.7 on 2021-08-02 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200830_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 9, 21, 52, 351104)),
        ),
    ]
