# Generated by Django 4.1.6 on 2023-05-20 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20210802_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 16, 59, 6, 55322)),
        ),
    ]
