# Generated by Django 4.2.1 on 2023-07-25 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_player_last_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='regnolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(blank=True, max_length=4000)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 10, 56, 9, 963110)),
        ),
    ]
