# Generated by Django 4.2.1 on 2023-07-25 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_player_last_submit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regnolist',
        ),
        migrations.AddField(
            model_name='player',
            name='regno',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 10, 58, 34, 608079)),
        ),
    ]
