# Generated by Django 4.2.1 on 2023-07-25 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_delete_regnolist_player_regno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='regno',
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='regno',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 11, 8, 6, 660985)),
        ),
    ]
