# Generated by Django 4.2.1 on 2023-07-25 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_player_regno_playerdetails_regno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 11, 8, 28, 899155)),
        ),
    ]
